name: Build and Deploy Docker Image
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    # TODO: consider using setup-qemu (https://github.com/docker/setup-qemu-action) to build for ARM as well as AMD64
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set docker image name
      run: echo "IMAGE_NAME=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    - name: Set docker image tag
      run: >
        echo "IMAGE_URL_HASH=${{env.IMAGE_NAME}}:${{ github.sha }}" >> $GITHUB_ENV;
        echo "IMAGE_URL=${{env.IMAGE_NAME}}:${{ github.sha }}" >> $GITHUB_ENV;
    - name: Conditionally also tag image as latest
      if: github.ref == 'refs/heads/main'
      run: echo "IMAGE_URL=${{env.IMAGE_URL}},${{env.IMAGE_NAME}}:latest" >> $GITHUB_ENV
    - name: Build and push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_URL }}
    - name: Conditionally deploy image to CapRover
      if: github.ref == 'refs/heads/main'
      uses: caprover/deploy-from-github@v1.1.2
      with:
        server: "${{ secrets.CAPROVER_SERVER }}"
        app: "${{ secrets.APP_NAME }}"
        token: "${{ secrets.APP_TOKEN }}"
        image: ${{ env.IMAGE_URL_HASH }}
